version: '3.9'

services:
  db:
    build: ./db/
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  flask:
    build: .
    command: gunicorn --bind 0.0.0.0:4200 main_instant:app
    restart: always
    volumes:
      - .:/app
    expose:
      - 4200

  nginx:
    build: ./nginx/
    ports:
      - 8080:8080
    depends_on:
      - flask
