version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pw
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:4200 main_instant:app
    restart: always
    volumes:
      - .:/app
    expose:
      - 4200
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8080:8080
    depends_on:
      - web
